global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8001']
  - job_name: 'freqtrade'
    static_configs:
      - targets: ['freqtrade:8080']